[project]
name = "iontheprize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "charset-normalizer>=3.4.2",
    "sympy>=1.14.0",
    "toml>=0.10.2",
    "tomlkit>=0.13.3",
]
